/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  mcavalli
 * Created: 09/11/2018
 */

CRATE TABLE TEMPLATE_DEPLOY(
ID INTEGER IDENTITY NOT NULL,
DESCRICAO VARCHAR(255) NOT NULL,
ID_TIPO_TRANSICAO SMALLINT NOT NULL,
DURACAO_TRANSICAO SMALLINT NOT NULL,
DURACAO_PROPAGANDA SMALLINT NOT NULL)




CREATE TABLE DEPLOY (
ID INTEGER IDENTITY NOT NULL,
ID_ESTABELECIMENTO INTEGER NOT NULL,
DESCRICAO VARCHAR(255) NOT NULL,
DATA TIMESTAMP NOT NULL,
DATA_VALIDADE TIMESTAMP NOT NULL,
SITUACAO SMALLINT NOT NULL,
ATIVO BOOLEAN NOT NULL)




CREATE TABLE DEPLOY_PROPAGANDA(
ID INTEGER IDENTITY NOT NULL,
ID_DEPLOY INTEGER NOT NULL,
ID_CLIENTE_PROPAGANDA INTEGER NOT NULL,
ORDEM SMALLINT NOT NULL,
ID_TIPO_TRANSICAO SMALLINT NOT NULL,
DURACAO_TRANSICAO SMALLINT NOT NULL,
DURACAO_PROPAGANDA SMALLINT NOT NULL,
ID_TIPO_MIDIA SMALLINT NOT NULL)